[package]
name = "md-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31"                    # GUI framework (includes egui)  
egui_commonmark = { version = "0.20", features = ["better_syntax_highlighting"] }  
